In [29]:
import pandas
import numpy as np

In [2]:
#Single 1D Array
# Create a Series from a list
data = [10, 20, 30, 40, 50]
s = pd.Series(data)
print(s.iloc[3])
print(s[1:4])

40
1    20
2    30
3    40
dtype: int64


In [7]:
#Definition of Dictionary X
x = {'Name': ['Rose','John', 'Jane', 'Mary'], 'ID': [1, 2, 3, 4], 'Department': ['Architect Group', 'Software Group', 'Design Team', 'Infrastructure'], 
      'Salary':[100000, 80000, 50000, 60000]}

#casting the dictionary to a DataFrame
df = pd.DataFrame(x)
x = df[['ID','Name']]

print(x)
#display the result df
print(type(df))
print(type(x))
print(df)

   ID  Name
0   1  Rose
1   2  John
2   3  Jane
3   4  Mary
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
   Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000


In [27]:
a = {'Student':['David', 'Samuel', 'Terry', 'Evan'],
     'Age':['27', '24', '22', '32'],
     'Country':['UK', 'Canada', 'China', 'USA'],
     'Course':['Python','Data Structures','Machine Learning','Web Development'],
     'Marks':['85','72','89','76']}
df1 = pd.DataFrame(a)
df1
    
b = df1[["Marks"]]
c = df1[["Country","Course"]]

print(df1.loc[1,"Marks"])
print(df1.iloc[0,0])
print(df1)
df1.iloc[1:3,0]

72
David
  Student Age Country            Course Marks
0   David  27      UK            Python    85
1  Samuel  24  Canada   Data Structures    72
2   Terry  22   China  Machine Learning    89
3    Evan  32     USA   Web Development    76


1    Samuel
2     Terry
Name: Student, dtype: object

In [40]:
a = np.array([0, 1, 2, 3, 4])
b = np.array([[0,1],[2,34]])
c = np.array([[2,1],[33,6]])
def print_properties(np_array):
    print(type(np_array))
    print(np_array.ndim)
    print(np_array.shape)
    print(np_array.size)
    print(np_array)

print_properties(a)
print_properties(b)
print_properties(c) 

z = b + c
print(z)
z.T #no change since 2x2
print(z)
print(type(z))


<class 'numpy.ndarray'>
1
(5,)
5
[0 1 2 3 4]
<class 'numpy.ndarray'>
2
(2, 2)
4
[[ 0  1]
 [ 2 34]]
<class 'numpy.ndarray'>
2
(2, 2)
4
[[ 2  1]
 [33  6]]
[[ 2  2]
 [35 40]]
[[ 2  2]
 [35 40]]
<class 'numpy.ndarray'>


In [43]:
#splicing
X=np.array([[1,0,1],[2,2,2]]) 

out=X[0:2,2]
out

array([1, 2])

In [44]:
X=np.array([[1,0],[0,1]]) 

Y=np.array([[2,1],[1,2]]) 

Z=np.dot(X,Y) 
Z

array([[2, 1],
       [1, 2]])